// const axios = require('axios');
// const fs = require('fs');
// const cheerio = require('cheerio');
// const { bulkCreate } = require('./models/location');


// const scrapedLinks = [];
// const scrapedLocations = [];
// const linksToScrape = [
//     "http://hauntedhouses.com/locations/",
//     "http://hauntedhouses.com/locations/page/2/",
//     "http://hauntedhouses.com/locations/page/3/",
//     "http://hauntedhouses.com/locations/page/4/",
//     "http://hauntedhouses.com/locations/page/5/",
//     "http://hauntedhouses.com/locations/page/6/",
//     "http://hauntedhouses.com/locations/page/7/",
//     "http://hauntedhouses.com/locations/page/8/",
//     "http://hauntedhouses.com/locations/page/9/",
//     "http://hauntedhouses.com/locations/page/10/",
//     "http://hauntedhouses.com/locations/page/11/",
//     "http://hauntedhouses.com/locations/page/12/",
//     "http://hauntedhouses.com/locations/page/13/",
//     "http://hauntedhouses.com/locations/page/14/",
//     "http://hauntedhouses.com/locations/page/15/",
//     "http://hauntedhouses.com/locations/page/16/",
//     "http://hauntedhouses.com/locations/page/17/",
//     "http://hauntedhouses.com/locations/page/18/",
//     "http://hauntedhouses.com/locations/page/19/",
//     "http://hauntedhouses.com/locations/page/20/",
//     "http://hauntedhouses.com/locations/page/21/",
//     "http://hauntedhouses.com/locations/page/22/",
//     "http://hauntedhouses.com/locations/page/23/",
//     "http://hauntedhouses.com/locations/page/24/",
//     "http://hauntedhouses.com/locations/page/25/",
//     "http://hauntedhouses.com/locations/page/26/",
//     "http://hauntedhouses.com/locations/page/27/",
//     "http://hauntedhouses.com/locations/page/28/",
//     "http://hauntedhouses.com/locations/page/29/",
//     "http://hauntedhouses.com/locations/page/30/",
//     "http://hauntedhouses.com/locations/page/31/",
//     "http://hauntedhouses.com/locations/page/32/",
//     "http://hauntedhouses.com/locations/page/33/",
//     "http://hauntedhouses.com/locations/page/34/",
//     "http://hauntedhouses.com/locations/page/35/",
//     "http://hauntedhouses.com/locations/page/36/",
//     "http://hauntedhouses.com/locations/page/37/",
//     "http://hauntedhouses.com/locations/page/38/",
//     "http://hauntedhouses.com/locations/page/39/",
//     "http://hauntedhouses.com/locations/page/40/",
//     "http://hauntedhouses.com/locations/page/41/",
// ];

// const locationsToScrape = [
//     // "http://hauntedhouses.com/uncategorized/top-13/",
//     "http://hauntedhouses.com/west-virginia/harpers-ferry/",
//     "http://hauntedhouses.com/florida/polk-museum/",
//     "http://hauntedhouses.com/alaska/skagway-old-gold-rush-town/",
//     "http://hauntedhouses.com/virginia/williamsburg-colonial-homes/",
//     "http://hauntedhouses.com/district-of-columbia/the-white-house/",
//     "http://hauntedhouses.com/district-of-columbia/the-octagon-house-in-washington-d-c/",
//     "http://hauntedhouses.com/district-of-columbia/u-s-capitol-building/",
//     "http://hauntedhouses.com/colorado/molly-brown-house/",
//     "http://hauntedhouses.com/colorado/bradmar-tudor-manor/",
//     "http://hauntedhouses.com/colorado/stanley-hotel/",
//     "http://hauntedhouses.com/colorado/newhouse-hotel-2/",
//     "http://hauntedhouses.com/colorado/antlers-hilton/",
//     "http://hauntedhouses.com/colorado/hearthstone-inn/",
//     "http://hauntedhouses.com/colorado/pioneers-museum/",
//     "http://hauntedhouses.com/colorado/the-strada-building-2/",
//     "http://hauntedhouses.com/colorado/grant-humphreys-mansion-2/",
//     "http://hauntedhouses.com/colorado/denver-union-station-2/",
//     "http://hauntedhouses.com/colorado/denver-courthouse/",
//     "http://hauntedhouses.com/colorado/lumber-baron-inn-gardens/",
//     "http://hauntedhouses.com/colorado/black-american-west-museum/",
//     "http://hauntedhouses.com/colorado/colorado-grande-casino/",
//     "http://hauntedhouses.com/colorado/cripple-creek-jail/",
//     "http://hauntedhouses.com/colorado/palace-hotel/",
//     "http://hauntedhouses.com/colorado/boulder-theatre/",
//     "http://hauntedhouses.com/colorado/hotel-boulderado/",
//     "http://hauntedhouses.com/colorado/the-baldpate-inn/",
//     "http://hauntedhouses.com/colorado/hotel-colorado/",
//     "http://hauntedhouses.com/colorado/rosemount-museum/",
//     "http://hauntedhouses.com/alabama/saint-james-hotel-2/",
//     "http://hauntedhouses.com/alabama/sturdivant-hall/",
//     "http://hauntedhouses.com/alabama/fort-gaines/",
//     "http://hauntedhouses.com/alabama/montevallo-university/",
//     "http://hauntedhouses.com/alabama/lucas-tavern/",
//     "http://hauntedhouses.com/arkansas/the-old-state-house-museum/",
//     "http://hauntedhouses.com/arkansas/macarthur-military-museum/",
//     "http://hauntedhouses.com/arkansas/mount-holly-cemetery/",
//     "http://hauntedhouses.com/arkansas/crescent-hotel/",
//     "http://hauntedhouses.com/arkansas/old-allen-house/",
//     "http://hauntedhouses.com/arizona/jerome-grand-hotel/",
//     "http://hauntedhouses.com/arizona/the-connor-building/",
//     "http://hauntedhouses.com/arizona/mile-high-inn-and-grill/",
//     "http://hauntedhouses.com/arizona/coyote-joes-bar/",
//     "http://hauntedhouses.com/arizona/hassayampa-inn/",
//     "http://hauntedhouses.com/arizona/prescott-fine-arts-theatre/",
//     "http://hauntedhouses.com/arizona/vendome-hotel/",
//     "http://hauntedhouses.com/arizona/birdcage-theater/",
//     "http://hauntedhouses.com/arizona/big-nose-kates-saloon/",
//     "http://hauntedhouses.com/arizona/hotel-congress/",
//     "http://hauntedhouses.com/arizona/tucson-university-modern-language-arts-building/",
//     "http://hauntedhouses.com/arizona/velasco-pueblo/",
//     "http://hauntedhouses.com/arizona/copper-queen-hotel/",
//     "http://hauntedhouses.com/arizona/the-carleton-house-fort-huachuca/",
//     "http://hauntedhouses.com/california/bodie-cemetery/",
//     "http://hauntedhouses.com/california/bodie-state-historical-park-mines/",
//     "http://hauntedhouses.com/california/gregory-house-2/",
//     "http://hauntedhouses.com/california/mendocini-house/",
//     "http://hauntedhouses.com/california/john-s-cain-house/",
//     "http://hauntedhouses.com/california/bessie-loves-cabin/",
//     "http://hauntedhouses.com/california/the-comedy-store/",
//     "http://hauntedhouses.com/california/harlow-bern-house/",
//     "http://hauntedhouses.com/california/jean-harlows-westwood-home/",
//     "http://hauntedhouses.com/california/nelson-house/",
//     "http://hauntedhouses.com/california/the-hollywood-pantages-theater/",
//     "http://hauntedhouses.com/california/hollywood-roosevelt-hotel/",
//     "http://hauntedhouses.com/california/avalon-hollywood/",
//     "http://hauntedhouses.com/california/the-warner-pacific-theater/",
//     "http://hauntedhouses.com/california/colton-hall-museum-2/",
//     "http://hauntedhouses.com/california/presidio-chapel-and-rectory/",
//     "http://hauntedhouses.com/california/stokes-adobe/",
//     "http://hauntedhouses.com/california/el-campo-santo-cemetery/",
//     "http://hauntedhouses.com/california/casa-de-estudillo/",
//     "http://hauntedhouses.com/california/el-fandango-restaurant/",
//     "http://hauntedhouses.com/california/horton-grand-hotel/",
//     "http://hauntedhouses.com/california/hotel-del-coronado/",
//     "http://hauntedhouses.com/california/robinson-rose-house/",
//     "http://hauntedhouses.com/california/star-of-india/",
//     "http://hauntedhouses.com/california/stevenson-house/",
//     "http://hauntedhouses.com/california/bee-bennett-mansion/",
//     "http://hauntedhouses.com/california/cary-house-hotel/",
//     "http://hauntedhouses.com/california/cuppa-coffee-and-more/",
//     "http://hauntedhouses.com/california/fountain-tallman-soda-works-museum/",
//     "http://hauntedhouses.com/california/hangmans-tree-ice-cream-saloon/",
//     "http://hauntedhouses.com/california/sacramento-cemetery/",
//     "http://hauntedhouses.com/california/sacramento-library/",
//     "http://hauntedhouses.com/california/sacramento-theatre/",
//     "http://hauntedhouses.com/california/stanford-mansion/",
//     "http://hauntedhouses.com/california/the-whaley-house/",
//     "http://hauntedhouses.com/california/villa-montezuma/",
//     "http://hauntedhouses.com/california/alcatraz-prison-national-park/",
//     "http://hauntedhouses.com/california/nob-hill-inn/",
//     "http://hauntedhouses.com/california/the-queen-anne-hotel/",
//     "http://hauntedhouses.com/california/rose-hill-historical-cemetery/",
//     "http://hauntedhouses.com/california/the-union-hotel/",
//     "http://hauntedhouses.com/california/the-mission-san-antonio-de-padua/",
//     "http://hauntedhouses.com/california/the-santa-barbara-mission/",
//     "http://hauntedhouses.com/california/humboldt-brews/",
//     "http://hauntedhouses.com/california/stanley-ware-house/",
//     "http://hauntedhouses.com/california/the-queen-mary/",
//     "http://hauntedhouses.com/california/peninsula-school/",
//     "http://hauntedhouses.com/california/rengstorff-house/",
//     "http://hauntedhouses.com/california/the-cascade-theatre-in-redding/",
//     "http://hauntedhouses.com/california/mission-san-miguel/",
//     "http://hauntedhouses.com/connecticut/hill-stead-house/",
//     "http://hauntedhouses.com/connecticut/hartford-huguenot-house-museum/",
//     "http://hauntedhouses.com/connecticut/hartford-twain-house/",
//     "http://hauntedhouses.com/connecticut/hale-hale-house/",
//     "http://hauntedhouses.com/connecticut/phelps-mansion/",
//     "http://hauntedhouses.com/connecticut/curtis-house-inn/",
//     "http://hauntedhouses.com/connecticut/glebe-house/",
//     "http://hauntedhouses.com/delaware/amstel-house/",
//     "http://hauntedhouses.com/delaware/david-finney-inn/",
//     "http://hauntedhouses.com/delaware/bellevue-hall-mansion/",
//     "http://hauntedhouses.com/delaware/dead-presidents-pub/",
//     "http://hauntedhouses.com/delaware/fort-delaware/",
//     "http://hauntedhouses.com/delaware/woodburn-mansion/",
//     "http://hauntedhouses.com/florida/luckys-tavern-formerly-coyote-ugly-saloon/",
//     "http://hauntedhouses.com/florida/king-cromartie-house/",
//     "http://hauntedhouses.com/florida/new-river-inn/",
//     "http://hauntedhouses.com/florida/stranahan-house/",
//     "http://hauntedhouses.com/florida/hemingway-house/",
//     "http://hauntedhouses.com/florida/little-white-house/",
//     "http://hauntedhouses.com/florida/key-west-resort/",
//     "http://hauntedhouses.com/florida/the-biltmore-hotel/",
//     "http://hauntedhouses.com/florida/colony-theater/",
//     "http://hauntedhouses.com/florida/miami-river-inn/",
//     "http://hauntedhouses.com/florida/villa-paula-mansion/",
//     "http://hauntedhouses.com/florida/casablanca-inn/",
//     "http://hauntedhouses.com/florida/flagler-college/",
//     "http://hauntedhouses.com/florida/o-c-whites-pub/",
//     "http://hauntedhouses.com/florida/saint-francis-inn/",
//     "http://hauntedhouses.com/florida/castillo-de-san-marcos/",
//     "http://hauntedhouses.com/florida/saint-augustine-jail/",
//     "http://hauntedhouses.com/florida/saint-augustine-lighthouse/",
//     "http://hauntedhouses.com/florida/the-scarlett-ohara-pub/",
//     "http://hauntedhouses.com/florida/boca-raton-resort-club/",
//     "http://hauntedhouses.com/florida/the-daytona-playhouse/",
//     "http://hauntedhouses.com/florida/colony-hotel/",
//     "http://hauntedhouses.com/florida/herlong-mansion/",
//     "http://hauntedhouses.com/florida/ashleys-of-rockledge/",
//     "http://hauntedhouses.com/florida/tampa-theatre/",
//     "http://hauntedhouses.com/georgia/17-hundred-90-restaurant-and-inn/",
//     "http://hauntedhouses.com/georgia/fort-pulaski/",
//     "http://hauntedhouses.com/georgia/william-kehoe-house/",
//     "http://hauntedhouses.com/georgia/pirates-house/",
//     "http://hauntedhouses.com/georgia/olde-pink-house/",
//     "http://hauntedhouses.com/georgia/jekyll-island-club-hotel/",
//     "http://hauntedhouses.com/georgia/kolb-ridge-court/",
//     "http://hauntedhouses.com/idaho/the-egyptian-theatre/",
//     "http://hauntedhouses.com/idaho/idaho-state-university/",
//     "http://hauntedhouses.com/idaho/pocatello-high-school/",
//     "http://hauntedhouses.com/idaho/idaho-state-penitentiary/",
//     "http://hauntedhouses.com/idaho/pioneer-boot-hill-cemetery/",
//     "http://hauntedhouses.com/idaho/petes-tavern/",
//     "http://hauntedhouses.com/illinois/biograph-theater/",
//     "http://hauntedhouses.com/illinois/national-pastime-theater/",
//     "http://hauntedhouses.com/illinois/cigars-and-stripes-hammer-hed-lounge/",
//     "http://hauntedhouses.com/illinois/hickory-hill-mansion/",
//     "http://hauntedhouses.com/illinois/rialto-theatre/",
//     "http://hauntedhouses.com/illinois/glessner-house/",
//     "http://hauntedhouses.com/illinois/ohenrys-roadhouse-building/",
//     "http://hauntedhouses.com/illinois/original-springs-hotel/",
//     "http://hauntedhouses.com/illinois/woodstock-opera-house/",
//     "http://hauntedhouses.com/indiana/hannah-house/",
//     "http://hauntedhouses.com/illinois/the-red-lion-pub/",
//     "http://hauntedhouses.com/illinois/the-ole-saint-andrews-inn/",
//     "http://hauntedhouses.com/illinois/saint-valentines-day-massacre/",
//     "http://hauntedhouses.com/indiana/indiana-central-state-hospital/",
//     "http://hauntedhouses.com/illinois/steak-joynt-building/",
//     "http://hauntedhouses.com/indiana/james-allison-mansion/",
//     "http://hauntedhouses.com/indiana/slippery-noodle-inn/",
//     "http://hauntedhouses.com/illinois/country-house-of-clarendon-hills/",
//     "http://hauntedhouses.com/indiana/rivoli-theatre/",
//     "http://hauntedhouses.com/indiana/indiana-university/",
//     "http://hauntedhouses.com/indiana/crown-point-sheriffs-house/",
//     "http://hauntedhouses.com/indiana/willard-library/",
//     "http://hauntedhouses.com/maine/captain-fairfield-inn/",
//     "http://hauntedhouses.com/maine/nonantum-resort/",
//     "http://hauntedhouses.com/maine/captain-lord-mansion/",
//     "http://hauntedhouses.com/indiana/whitley-haunted-jail/",
//     "http://hauntedhouses.com/maine/charles-q-clapp-house/",
//     "http://hauntedhouses.com/maine/mclellan-sweat-house/",
//     "http://hauntedhouses.com/maine/western-cemetery/",
//     "http://hauntedhouses.com/iowa/brucemore-mansion/",
//     "http://hauntedhouses.com/iowa/stuart-hall/",
//     "http://hauntedhouses.com/iowa/ambrose-hall/",
//     "http://hauntedhouses.com/iowa/blackhawk-hotel/",
//     "http://hauntedhouses.com/iowa/old-masonic-temple/",
//     "http://hauntedhouses.com/iowa/scott-city-hall/",
//     "http://hauntedhouses.com/iowa/the-grand-opera/",
//     "http://hauntedhouses.com/iowa/the-ham-house/",
//     "http://hauntedhouses.com/iowa/the-old-jail/",
//     "http://hauntedhouses.com/iowa/currier-hall/",
//     "http://hauntedhouses.com/kansas/broadview-hotel/",
//     "http://hauntedhouses.com/iowa/slater-hall-university-of-iowa/",
//     "http://hauntedhouses.com/iowa/squirrel-cage-jail/",
//     "http://hauntedhouses.com/maine/kennebunk-inn/",
//     "http://hauntedhouses.com/maine/east-wind-inn/",
//     "http://hauntedhouses.com/maryland/middleton-tavern/",
//     "http://hauntedhouses.com/maryland/uss-constellation/",
//     "http://hauntedhouses.com/maryland/tavern-at-clinton/",
//     "http://hauntedhouses.com/maryland/lilburn-mansion/",
//     "http://hauntedhouses.com/maryland/schifferstadt-museum/",
//     "http://hauntedhouses.com/maryland/hampton-house/",
//     "http://hauntedhouses.com/kansas/sauers-castle/",
//     "http://hauntedhouses.com/kansas/strawberry-hill-mansion/",
//     "http://hauntedhouses.com/kansas/kansas-state-capitol/",
//     "http://hauntedhouses.com/kansas/east-stadium-kansas-state-university/",
//     "http://hauntedhouses.com/kansas/old-saint-mary-hospital/",
//     "http://hauntedhouses.com/kansas/topeka-high-school/",
//     "http://hauntedhouses.com/kansas/5-houses-at-fort-leavenworth/",
//     "http://hauntedhouses.com/kentucky/dupont-mansion/",
//     "http://hauntedhouses.com/massachusetts/barnstable-house/",
//     "http://hauntedhouses.com/massachusetts/old-yarmouth-inn/",
//     "http://hauntedhouses.com/massachusetts/deerfield-inn/",
//     "http://hauntedhouses.com/massachusetts/deerfield-old-burial-grounds/",
//     "http://hauntedhouses.com/massachusetts/lizzie-borden-house/",
//     "http://hauntedhouses.com/massachusetts/bishop-huntington-house/",
//     "http://hauntedhouses.com/kentucky/ashland-house/",
//     "http://hauntedhouses.com/kentucky/loudon-house/",
//     "http://hauntedhouses.com/kentucky/morgan-house/",
//     "http://hauntedhouses.com/kentucky/cabbage-patch-house/",
//     "http://hauntedhouses.com/kentucky/infirmary-for-women/",
//     "http://hauntedhouses.com/kentucky/the-jp-speed-mansion/",
//     "http://hauntedhouses.com/kentucky/the-monserrat/",
//     "http://hauntedhouses.com/kentucky/the-pink-palace/",
//     "http://hauntedhouses.com/kentucky/the-speed-art-museum/",
//     "http://hauntedhouses.com/kentucky/waverly-hills-sanitarium/",
//     "http://hauntedhouses.com/kentucky/maysville-hospital/",
//     "http://hauntedhouses.com/kentucky/the-washington-opera-house/",
//     "http://hauntedhouses.com/kentucky/western-kentucky-university/",
//     "http://hauntedhouses.com/kentucky/liberty-hall-mansion/",
//     "http://hauntedhouses.com/kentucky/southgate-house/",
//     "http://hauntedhouses.com/kentucky/bobby-mackeys-music-world/",
//     "http://hauntedhouses.com/louisiana/the-columns-mansion/",
//     "http://hauntedhouses.com/louisiana/dauphine-orleans-hotel/",
//     "http://hauntedhouses.com/louisiana/provincial-hotel/",
//     "http://hauntedhouses.com/louisiana/st-louis-cathedral/",
//     "http://hauntedhouses.com/louisiana/monteleone-hotel/",
//     "http://hauntedhouses.com/louisiana/alibi-bar/",
//     "http://hauntedhouses.com/louisiana/lafittes-guest-house/",
//     "http://hauntedhouses.com/louisiana/lafittes-blacksmith-shop/",
//     "http://hauntedhouses.com/louisiana/le-pavilion-hotel/",
//     "http://hauntedhouses.com/louisiana/old-absinthe-house/",
//     "http://hauntedhouses.com/louisiana/laveau-house/",
//     "http://hauntedhouses.com/louisiana/destrehan-plantation/",
//     "http://hauntedhouses.com/louisiana/hermann-grima-house/",
//     "http://hauntedhouses.com/louisiana/st-louis-cemetery/",
//     "http://hauntedhouses.com/massachusetts/the-hawthorne-hotel/",
//     "http://hauntedhouses.com/louisiana/beauregard-keyes-house/",
//     "http://hauntedhouses.com/massachusetts/house-of-the-seven-gables-museum/",
//     "http://hauntedhouses.com/louisiana/tfreres-house/",
//     "http://hauntedhouses.com/massachusetts/joshua-ward-house/",
//     "http://hauntedhouses.com/louisiana/louisiana-saint-francisville-myrtles-plantation/",
//     "http://hauntedhouses.com/massachusetts/the-morgan-house/",
//     "http://hauntedhouses.com/louisiana/oak-alley-plantation/",
//     "http://hauntedhouses.com/massachusetts/ashley-house/",
//     "http://hauntedhouses.com/massachusetts/longfellows-wayside-inn/",
//     "http://hauntedhouses.com/massachusetts/colonial-house-inn/",
//     "http://hauntedhouses.com/louisiana/madam-lalauries-mansion/",
//     "http://hauntedhouses.com/michigan/allegan-jail/",
//     "http://hauntedhouses.com/michigan/regent-theatre/",
//     "http://hauntedhouses.com/michigan/kalamazoo-civic-theatre/",
//     "http://hauntedhouses.com/michigan/kalamazoo-sanitarium/",
//     "http://hauntedhouses.com/tennessee/belmont-mansion/",
//     "http://hauntedhouses.com/tennessee/capitol-records/",
//     "http://hauntedhouses.com/tennessee/market-street-brewery/",
//     "http://hauntedhouses.com/tennessee/the-hermitage/",
//     "http://hauntedhouses.com/tennessee/hunt-phelan-house/",
//     "http://hauntedhouses.com/tennessee/ernestine-and-hazels/",
//     "http://hauntedhouses.com/tennessee/orpheum-theatre/",
//     "http://hauntedhouses.com/texas/the-alamo/",
//     "http://hauntedhouses.com/tennessee/woodruff-fontaine-house/",
//     "http://hauntedhouses.com/texas/the-alamodome/",
//     "http://hauntedhouses.com/texas/the-alamo-street-restaurant-and-theater/",
//     "http://hauntedhouses.com/tennessee/carnton-mansion/",
//     "http://hauntedhouses.com/texas/the-menger-hotel/",
//     "http://hauntedhouses.com/texas/crazy-water-retirement-hotel/",
//     "http://hauntedhouses.com/texas/del-frisco-steakhouse/",
//     "http://hauntedhouses.com/texas/miss-mollys-bb/",
//     "http://hauntedhouses.com/texas/the-scott-theatre/",
//     "http://hauntedhouses.com/texas/natatorium/",
//     "http://hauntedhouses.com/texas/uss-lexington/",
//     "http://hauntedhouses.com/texas/hotel-adolphus/",
//     "http://hauntedhouses.com/texas/ashton-villa-mansion/",
//     "http://hauntedhouses.com/texas/baker-hotel/",
//     "http://hauntedhouses.com/texas/catfish-plantation/",
//     "http://hauntedhouses.com/michigan/columbia-court-apartment/",
//     "http://hauntedhouses.com/michigan/capitol-theater/",
//     "http://hauntedhouses.com/michigan/german-castle/",
//     "http://hauntedhouses.com/michigan/lansing-state-capitol-building/",
//     "http://hauntedhouses.com/michigan/fort-mackinac/",
//     "http://hauntedhouses.com/michigan/national-house-inn/",
//     "http://hauntedhouses.com/michigan/river-raisin-battlefield/",
//     "http://hauntedhouses.com/michigan/osceola-inn/",
//     "http://hauntedhouses.com/michigan/bowers-harbor-inn/",
//     "http://hauntedhouses.com/utah/ben-lomond-suites/",
//     "http://hauntedhouses.com/utah/peerys-egyptian-theater/",
//     "http://hauntedhouses.com/utah/prospect-gallery/",
//     "http://hauntedhouses.com/utah/union-train-station/",
//     "http://hauntedhouses.com/utah/egyptian-theater/",
//     "http://hauntedhouses.com/utah/park-city-silver-coalition-mine-the-ontario-silver-mine/",
//     "http://hauntedhouses.com/utah/brigham-young-farm-house/",
//     "http://hauntedhouses.com/utah/jewkes-draper-house/",
//     "http://hauntedhouses.com/utah/rio-grande-railroad-depot/",
//     "http://hauntedhouses.com/utah/mccune-mansion/",
//     "http://hauntedhouses.com/utah/shilo-inn/",
//     "http://hauntedhouses.com/utah/the-smith-house/",
//     "http://hauntedhouses.com/utah/idle-isle-cafe/",
//     "http://hauntedhouses.com/utah/cove-fort/",
//     "http://hauntedhouses.com/minnesota/first-avenue-night-club/",
//     "http://hauntedhouses.com/utah/moores-old-pine-inn/",
//     "http://hauntedhouses.com/virginia/colonel-michael-swope-townhouse/",
//     "http://hauntedhouses.com/minnesota/minneapolis-city-hall/",
//     "http://hauntedhouses.com/minnesota/minneapolis-institute-of-art/",
//     "http://hauntedhouses.com/virginia/gadsbys-tavern-museum/",
//     "http://hauntedhouses.com/minnesota/tyrone-guthrie-theater/",
//     "http://hauntedhouses.com/virginia/robert-e-lee-mansion/",
//     "http://hauntedhouses.com/minnesota/fitzgerald-theater/",
//     "http://hauntedhouses.com/virginia/the-william-ramsey-house/",
//     "http://hauntedhouses.com/vermont/bowman-house/",
//     "http://hauntedhouses.com/vermont/old-stagecoach-inn/",
//     "http://hauntedhouses.com/virginia/castle-hill-manor/",
//     "http://hauntedhouses.com/virginia/the-wickham-farmhouse/",
//     "http://hauntedhouses.com/virginia/the-henry-hill-house/",
//     "http://hauntedhouses.com/virginia/manassas-national-battlefield-park/",
//     "http://hauntedhouses.com/virginia/olde-town-inn-in-manassas/",
//     "http://hauntedhouses.com/virginia/the-stone-house/",
//     "http://hauntedhouses.com/virginia/portsmouth-gaffos-house/",
//     "http://hauntedhouses.com/virginia/glen-coe-bed-breakfast/",
//     "http://hauntedhouses.com/virginia/moore-house/",
//     "http://hauntedhouses.com/virginia/berkeley-plantation/",
//     "http://hauntedhouses.com/virginia/kenmore-plantation/",
//     "http://hauntedhouses.com/virginia/warren-sipe-house/",
//     "http://hauntedhouses.com/virginia/gunston-hall/",
//     "http://hauntedhouses.com/virginia/occoquan-inn-and-down-under-tavern/",
//     "http://hauntedhouses.com/virginia/waverly-house/",
//     "http://hauntedhouses.com/virginia/adam-thoroughgood-house/",
//     "http://hauntedhouses.com/washington/ann-starrett-mansion/",
//     "http://hauntedhouses.com/washington/ft-worden-commanding-officers-quarters-museum/",
//     "http://hauntedhouses.com/washington/fort-worden-guard-house/",
//     "http://hauntedhouses.com/washington/the-palace-hotel/",
//     "http://hauntedhouses.com/washington/the-james-and-hastings-building/",
//     "http://hauntedhouses.com/washington/manresa-castle/",
//     "http://hauntedhouses.com/washington/rothschild-house/",
//     "http://hauntedhouses.com/washington/harvard-exit-theater/",
//     "http://hauntedhouses.com/washington/hotel-andra/",
//     "http://hauntedhouses.com/washington/fort-vancouver-officers-row/",
//     "http://hauntedhouses.com/washington/pike-place-market/",
//     "http://hauntedhouses.com/minnesota/forepaughs-restaurant/",
//     "http://hauntedhouses.com/washington/seattle-central-community-college/",
//     "http://hauntedhouses.com/minnesota/gibbs-farmhouse/",
//     "http://hauntedhouses.com/washington/double-tree-inn/",
//     "http://hauntedhouses.com/washington/monaghan-hall/",
//     "http://hauntedhouses.com/minnesota/griggs-mansion/",
//     "http://hauntedhouses.com/washington/patsy-clark-mansion/",
//     "http://hauntedhouses.com/washington/washington-tacoma-fort-lewis/",
//     "http://hauntedhouses.com/washington/old-tacoma-city-hall/",
//     "http://hauntedhouses.com/washington/pantages-theatre/",
//     "http://hauntedhouses.com/washington/the-pagoda-on-five-mile-drive/",
//     "http://hauntedhouses.com/washington/uss-turner-joy/",
//     "http://hauntedhouses.com/washington/central-washington-university/",
//     "http://hauntedhouses.com/minnesota/landmark-center/",
//     "http://hauntedhouses.com/mississippi/monmouth-plantation/",
//     "http://hauntedhouses.com/minnesota/wabasha-street-caves/",
//     "http://hauntedhouses.com/mississippi/kings-tavern/",
//     "http://hauntedhouses.com/minnesota/thayers-bb/",
//     "http://hauntedhouses.com/mississippi/anchuca-mansion/",
//     "http://hauntedhouses.com/mississippi/cedar-grove-mansion/",
//     "http://hauntedhouses.com/mississippi/gregory-house/",
//     "http://hauntedhouses.com/minnesota/leduc-mansion/",
//     "http://hauntedhouses.com/minnesota/mantorville-opera-house/",
//     "http://hauntedhouses.com/minnesota/new-york-mills-regional-cultural-center/",
//     "http://hauntedhouses.com/mississippi/chapel-of-the-cross/",
//     "http://hauntedhouses.com/minnesota/kahler-grand-hotel/",
//     "http://hauntedhouses.com/west-virginia/west-virginia-penitentiary/",
//     "http://hauntedhouses.com/west-virginia/capitol-plaza-theatre/",
//     "http://hauntedhouses.com/west-virginia/city-of-parkersburg/",
//     "http://hauntedhouses.com/wisconsin/riverside-theater/",
//     "http://hauntedhouses.com/wisconsin/rave-eagles-club/",
//     "http://hauntedhouses.com/wisconsin/pfister-hotel/",
//     "http://hauntedhouses.com/wisconsin/the-brumder-mansion/",
//     "http://hauntedhouses.com/wisconsin/the-bar-next-door/",
//     "http://hauntedhouses.com/wisconsin/science-hall-at-university-of-wisconsin/",
//     "http://hauntedhouses.com/wisconsin/memorial-union/",
//     "http://hauntedhouses.com/wisconsin/octagon-house/",
//     "http://hauntedhouses.com/wisconsin/galloway-house-and-village/",
//     "http://hauntedhouses.com/wyoming/atlas-theatre/",
//     "http://hauntedhouses.com/wyoming/plains-hotel/",
//     "http://hauntedhouses.com/wyoming/saint-marks-episcopal-church/",
//     "http://hauntedhouses.com/wyoming/knight-hall-at-laramie-university/",
//     "http://hauntedhouses.com/wyoming/laramie-prison/",
//     "http://hauntedhouses.com/wisconsin/old-baraboo-inn/",
//     "http://hauntedhouses.com/wisconsin/hearthstone-historic-house/",
//     "http://hauntedhouses.com/wisconsin/stones-throw-entertainment-center/",
//     "http://hauntedhouses.com/wisconsin/the-kewaunee-inn/",
//     "http://hauntedhouses.com/wisconsin/mabel-tainter-theater/",
//     "http://hauntedhouses.com/wisconsin/walker-house/",
//     "http://hauntedhouses.com/wisconsin/the-grand-opera-house/",
//     "http://hauntedhouses.com/wisconsin/hotel-mead/",
//     "http://hauntedhouses.com/wyoming/lake-hotel/",
//     "http://hauntedhouses.com/wyoming/the-old-faithful-inn/",
//     "http://hauntedhouses.com/wyoming/irma-hotel/",
//     "http://hauntedhouses.com/wyoming/fort-bridger/",
//     "http://hauntedhouses.com/wyoming/wyoming-plains/",
//     "http://hauntedhouses.com/wyoming/virginian-hotel/",
//     "http://hauntedhouses.com/wyoming/wyoming-frontier-prison/",
//     "http://hauntedhouses.com/wyoming/kendrick-mansion/",
//     "http://hauntedhouses.com/rhode-island/astors-beechwood-mansion/",
//     "http://hauntedhouses.com/rhode-island/belcourt-castle/",
//     "http://hauntedhouses.com/rhode-island/breakers-mansion/",
//     "http://hauntedhouses.com/rhode-island/firehouse-theater/",
//     "http://hauntedhouses.com/rhode-island/jail-house-inn/",
//     "http://hauntedhouses.com/rhode-island/newport-art-museum-and-art-association-john-griswold-mansion/",
//     "http://hauntedhouses.com/rhode-island/viking-hotel/",
//     "http://hauntedhouses.com/rhode-island/redwood-library-and-anthenaeum/",
//     "http://hauntedhouses.com/rhode-island/the-pilgrim-inn-bb/",
//     "http://hauntedhouses.com/rhode-island/white-horse-tavern/",
//     "http://hauntedhouses.com/south-dakota/adams-house/",
//     "http://hauntedhouses.com/south-dakota/bullock-hotel/",
//     "http://hauntedhouses.com/south-dakota/villa-theresa-house/",
//     "http://hauntedhouses.com/south-dakota/hotel-alex-johnson/",
//     "http://hauntedhouses.com/south-dakota/orpheum-theater/",
//     "http://hauntedhouses.com/south-dakota/mount-marty-college/",
//     "http://hauntedhouses.com/south-carolina/battery-carriage-house-inn/",
//     "http://hauntedhouses.com/south-carolina/legare-street-house/",
//     "http://hauntedhouses.com/south-carolina/meeting-street-inn/",
//     "http://hauntedhouses.com/south-carolina/talvande-mansion/",
//     "http://hauntedhouses.com/pennsylvania/cedar-crest-college/",
//     "http://hauntedhouses.com/pennsylvania/king-george-inn/",
//     "http://hauntedhouses.com/pennsylvania/muhlenberg-college/",
//     "http://hauntedhouses.com/pennsylvania/bethlehem-hotel/",
//     "http://hauntedhouses.com/pennsylvania/sun-inn/",
//     "http://hauntedhouses.com/pennsylvania/churchmans-business-school-building/",
//     "http://hauntedhouses.com/pennsylvania/morovian-college/",
//     "http://hauntedhouses.com/pennsylvania/the-easton-library/",
//     "http://hauntedhouses.com/pennsylvania/easton-haunted-theater/",
//     "http://hauntedhouses.com/pennsylvania/farnsworth-house/",
//     "http://hauntedhouses.com/pennsylvania/gettysburg-battlefield/",
//     "http://hauntedhouses.com/pennsylvania/jennie-wade-house/",
//     "http://hauntedhouses.com/pennsylvania/new-hope-art-center/",
//     "http://hauntedhouses.com/pennsylvania/black-bass-hotel/",
//     "http://hauntedhouses.com/pennsylvania/aaron-burr-house/",
//     "http://hauntedhouses.com/pennsylvania/logan-inn/",
//     "http://hauntedhouses.com/pennsylvania/parry-mansion/",
//     "http://hauntedhouses.com/pennsylvania/phillips-mill/",
//     "http://hauntedhouses.com/pennsylvania/cashtown-inn/",
//     "http://hauntedhouses.com/pennsylvania/mcclellan-pomeroy-house/",
//     "http://hauntedhouses.com/pennsylvania/nickys-pub/",
//     "http://hauntedhouses.com/pennsylvania/battles-farm-house/",
//     "http://hauntedhouses.com/pennsylvania/pittsburgh-cemetery/",
//     "http://hauntedhouses.com/missouri/benton-high-school/",
//     "http://hauntedhouses.com/missouri/central-high-school-2/",
//     "http://hauntedhouses.com/missouri/the-social-parlor/",
//     "http://hauntedhouses.com/missouri/glore-psychiatric-museum/",
//     "http://hauntedhouses.com/missouri/lemp-mansion/",
//     "http://hauntedhouses.com/missouri/president-trumans-house/",
//     "http://hauntedhouses.com/missouri/guibourd-valle-house/",
//     "http://hauntedhouses.com/missouri/landers-theater/",
//     "http://hauntedhouses.com/montana/alberta-bair-theater/",
//     "http://hauntedhouses.com/montana/dude-rancher-lodge/",
//     "http://hauntedhouses.com/montana/julianos-restaurant/",
//     "http://hauntedhouses.com/montana/moss-mansion-historic/",
//     "http://hauntedhouses.com/montana/parmly-billings-library/",
//     "http://hauntedhouses.com/montana/rex-restaurant/",
//     "http://hauntedhouses.com/montana/rocky-mountain-college/",
//     "http://hauntedhouses.com/montana/western-heritage-center/",
//     "http://hauntedhouses.com/montana/butte-courthouse/",
//     "http://hauntedhouses.com/montana/club-13-bar/",
//     "http://hauntedhouses.com/montana/copper-king-mansion/",
//     "http://hauntedhouses.com/montana/the-dumas-brothel-bed-breakfast/",
//     "http://hauntedhouses.com/montana/hennessy-mansion/",
//     "http://hauntedhouses.com/montana/the-rookwood-speakeasy/",
//     "http://hauntedhouses.com/montana/the-world-museum-of-mining-orphan-girl-mine/",
//     "http://hauntedhouses.com/oregon/bagdad-theater-and-pub/",
//     "http://hauntedhouses.com/oregon/the-benson-hotel/",
//     "http://hauntedhouses.com/oregon/the-crystal-ballroom/",
//     "http://hauntedhouses.com/oregon/the-pittock-mansion-museum/",
//     "http://hauntedhouses.com/oregon/portlands-shanghai-tunnels/",
//     "http://hauntedhouses.com/oregon/saint-johns-twin-cinema-and-pub/",
//     "http://hauntedhouses.com/oregon/white-eagle-pub-and-hotel/",
//     "http://hauntedhouses.com/oregon/the-elsinore-theatre/",
//     "http://hauntedhouses.com/oregon/historic-bush-house-museum/",
//     "http://hauntedhouses.com/oregon/oregon-state-capitol/",
//     "http://hauntedhouses.com/oregon/willamette-heritage-center-mission-mills-museum/",
//     "http://hauntedhouses.com/oregon/geiser-grand-hotel/",
//     "http://hauntedhouses.com/oregon/heceta-house/",
//     "http://hauntedhouses.com/montana/meade-hotel/",
//     "http://hauntedhouses.com/montana/the-historic-hotel-metlen/",
//     "http://hauntedhouses.com/oregon/the-mcloughlin-house-and-barclay-house/",
//     "http://hauntedhouses.com/montana/klondike-bar-restaurant-and-casino/",
//     "http://hauntedhouses.com/oregon/wolf-creek-inn/",
//     "http://hauntedhouses.com/montana/brantley-mansion/",
//     "http://hauntedhouses.com/montana/little-bighorn-battlefield/",
//     "http://hauntedhouses.com/montana/carroll-college/",
//     "http://hauntedhouses.com/montana/grandstreet-theatre/",
//     "http://hauntedhouses.com/montana/bannack-ghost-town/",
//     "http://hauntedhouses.com/montana/kleinschmidt-house/",
//     "http://hauntedhouses.com/montana/tc-power-mansion/",
//     "http://hauntedhouses.com/oklahoma/mason-childrens-home/",
//     "http://hauntedhouses.com/nebraska/the-nebraska-state-capitol/",
//     "http://hauntedhouses.com/oklahoma/stone-lion-inn/",
//     "http://hauntedhouses.com/oklahoma/county-line-bbq-restaurant/",
//     "http://hauntedhouses.com/nebraska/temple-theatre/",
//     "http://hauntedhouses.com/oklahoma/langston-western-store/",
//     "http://hauntedhouses.com/nebraska/central-high-school/",
//     "http://hauntedhouses.com/oklahoma/skirvin-hotel/",
//     "http://hauntedhouses.com/nebraska/white-house-apartments/",
//     "http://hauntedhouses.com/oklahoma/fort-washita/",
//     "http://hauntedhouses.com/oklahoma/gilcrease-house/",
//     "http://hauntedhouses.com/nevada/abraham-curry-house/",
//     "http://hauntedhouses.com/nevada/bliss-mansion/",
//     "http://hauntedhouses.com/nevada/brewery-arts-center/",
//     "http://hauntedhouses.com/nevada/nevada-governors-mansion/",
//     "http://hauntedhouses.com/nevada/carson-city-mint/",
//     "http://hauntedhouses.com/nevada/thomas-j-edwards-house/",
//     "http://hauntedhouses.com/nevada/levy-house/",
//     "http://hauntedhouses.com/nevada/washoe-courthouse/",
//     "http://hauntedhouses.com/nevada/crooked-house/",
//     "http://hauntedhouses.com/nevada/gold-hill-hotel/",
//     "http://hauntedhouses.com/nevada/mackay-mansion/",
//     "http://hauntedhouses.com/nevada/piper-opera-house/",
//     "http://hauntedhouses.com/nevada/saint-marys-art-and-retreat-center/",
//     "http://hauntedhouses.com/nevada/virginia-city-cemetery/",
//     "http://hauntedhouses.com/nevada/old-washoe-club/",
//     "http://hauntedhouses.com/ohio/cincinnati-music-hall/",
//     "http://hauntedhouses.com/ohio/loveland-castle/",
//     "http://hauntedhouses.com/ohio/stenton-house/",
//     "http://hauntedhouses.com/ohio/franklin-castle/",
//     "http://hauntedhouses.com/ohio/squires-castle/",
//     "http://hauntedhouses.com/ohio/fort-hayes-school/",
//     "http://hauntedhouses.com/ohio/harrison-house/",
//     "http://hauntedhouses.com/ohio/james-thurber-house/",
//     "http://hauntedhouses.com/ohio/ohio-governors-mansion-lindenburg-house/",
//     "http://hauntedhouses.com/ohio/kelton-house/",
//     "http://hauntedhouses.com/ohio/united-states-air-force-museum/",
//     "http://hauntedhouses.com/ohio/air-force-museum-b-29-bomber-bockscar/",
//     "http://hauntedhouses.com/ohio/air-force-museum-lady-be-good/",
//     "http://hauntedhouses.com/ohio/air-force-museum-strawberry-bitch/",
//     "http://hauntedhouses.com/ohio/victoria-theatre/",
//     "http://hauntedhouses.com/ohio/collingwood-art-center/",
//     "http://hauntedhouses.com/ohio/maumee-bay-brewing-company/",
//     "http://hauntedhouses.com/ohio/9726/",
//     "http://hauntedhouses.com/ohio/garfield-house/",
//     "http://hauntedhouses.com/ohio/ohio-state-reformatory/",
//     "http://hauntedhouses.com/new-hampshire/tuck-museum-complex/",
//     "http://hauntedhouses.com/new-hampshire/henniker-house/",
//     "http://hauntedhouses.com/new-hampshire/admiral-hawleys-house/",
//     "http://hauntedhouses.com/new-hampshire/john-paul-jones-house/",
//     "http://hauntedhouses.com/new-hampshire/point-of-graves-burial-ground/",
//     "http://hauntedhouses.com/new-hampshire/portsmouth-music-hall/",
//     "http://hauntedhouses.com/new-hampshire/rockingham-hotel/",
//     "http://hauntedhouses.com/new-hampshire/portsmouth-sheafe-street-inn/",
//     "http://hauntedhouses.com/new-hampshire/sise-inn/",
//     "http://hauntedhouses.com/new-jersey/southern-mansion/",
//     "http://hauntedhouses.com/new-jersey/new-jersey-cape-may-queens-hotel/",
//     "http://hauntedhouses.com/new-jersey/darress-theatre/",
//     "http://hauntedhouses.com/new-jersey/burlington-prison-museum/",
//     "http://hauntedhouses.com/new-jersey/evert-van-wickle-house/",
//     "http://hauntedhouses.com/new-jersey/ocean-city-bed-breakfast/",
//     "http://hauntedhouses.com/new-jersey/ringwood-manor/",
//     "http://hauntedhouses.com/oklahoma/fort-sill-2/",
//     "http://hauntedhouses.com/new-jersey/the-flanders-hotel/",
//     "http://hauntedhouses.com/new-mexico/kimo-theater/",
//     "http://hauntedhouses.com/new-mexico/wool-warehouse-theater/",
//     "http://hauntedhouses.com/new-mexico/saint-james-hotel/",
//     "http://hauntedhouses.com/new-mexico/the-lodge/",
//     "http://hauntedhouses.com/new-mexico/la-posada/",
//     "http://hauntedhouses.com/north-carolina/mordecai-manor/",
//     "http://hauntedhouses.com/north-carolina/old-state-capitol-building/",
//     "http://hauntedhouses.com/north-carolina/andrew-johnson-home/",
//     "http://hauntedhouses.com/north-carolina/reed-house/",
//     "http://hauntedhouses.com/north-carolina/duke-mansion/",
//     "http://hauntedhouses.com/north-carolina/teachs-hole/",
//     "http://hauntedhouses.com/north-carolina/thalian-hall/",
//     "http://hauntedhouses.com/north-dakota/former-governors-mansion/",
//     "http://hauntedhouses.com/north-dakota/library-memorial-building/",
//     "http://hauntedhouses.com/north-dakota/bismarck-church/",
//     "http://hauntedhouses.com/new-york/gay-street-ghosts/",
//     "http://hauntedhouses.com/north-dakota/peacock-alley-bar-grill-and-the-patterson-hotel/",
//     "http://hauntedhouses.com/new-york/the-palace-theater/",
//     "http://hauntedhouses.com/new-york/morris-jumel-mansion/",
//     "http://hauntedhouses.com/north-dakota/custer-house/",
//     "http://hauntedhouses.com/new-york/poughkeepsie-church/",
//     "http://hauntedhouses.com/north-dakota/fort-abercrombie/",
//     "http://hauntedhouses.com/new-york/poughkeepsie-college/",
//     "http://hauntedhouses.com/north-dakota/yunker-farm-childrens-museum/",
//     "http://hauntedhouses.com/new-york/thayer-home/",
//     "http://hauntedhouses.com/iowa/9503/",
//     "http://hauntedhouses.com/new-york/west-point/",
//     "http://hauntedhouses.com/new-york/albany-state-capitol/",
//     "http://hauntedhouses.com/california/the-cosmopolitan-hotel-and-restaurant/",
//     "http://hauntedhouses.com/new-york/uss-the-sullivans-dd57/",
//     "http://hauntedhouses.com/california/the-uss-iowa-b-16-museum/",
//     "http://hauntedhouses.com/new-york/chateau-at-coindre-hall/",
//     "http://hauntedhouses.com/new-york/montauk-manor/",
//     "http://hauntedhouses.com/new-york/shanley-hotel/",
//     "http://hauntedhouses.com/new-york/the-pine-bush-house/",
//     "http://hauntedhouses.com/new-york/the-vanderbilt-house-hotel-restaurant/",
//     "http://hauntedhouses.com/new-york/raynham-hall-museum/",
//     "http://hauntedhouses.com/new-york/fort-stanwix/",
//     "http://hauntedhouses.com/new-york/katies-of-smithtown/",
//     "http://hauntedhouses.com/new-york/syracuse-theatre/",
//     "http://hauntedhouses.com/new-york/stanley-theatre/",
//     "http://hauntedhouses.com/new-york/valentown-hall/",
//     "http://hauntedhouses.com/oregon/ashland-springs-hotel/",
//     "http://hauntedhouses.com/washington/captain-edwin-r-rogers-house/",
//     "http://hauntedhouses.com/washington/bair-bistro/",
//     "http://hauntedhouses.com/nebraska/brother-sebastians-restaurant-and-winery/",
//     "http://hauntedhouses.com/nebraska/captain-benson-bailey-house-museum/",
//     "http://hauntedhouses.com/nebraska/the-museum-of-shadows/",
//     "http://hauntedhouses.com/nebraska/joslyn-castle/",
//     "http://hauntedhouses.com/nebraska/cornerstone-mansion-bed-breakfast/",
//     "http://hauntedhouses.com/nebraska/neville-center-for-performing-arts/",
//     "http://hauntedhouses.com/nebraska/buffalo-bill-ranch-state-historical-park/",
//     "http://hauntedhouses.com/kansas/kansas-aviation-museum/",
//     "http://hauntedhouses.com/kansas/eldridge-hotel/",
//     "http://hauntedhouses.com/kansas/senate-luxury-suites-hotel/",
//     "http://hauntedhouses.com/california/bodie-ghost-town/",
//     "http://hauntedhouses.com/virginia/trinity-episcopal-church/",
//     "http://hauntedhouses.com/virginia/york-hall-nelson-house/",
//     "http://hauntedhouses.com/missouri/folly-theatre/",
//     "http://hauntedhouses.com/nevada/mob-museum/",
//     "http://hauntedhouses.com/idaho/enders-hotel/",
//     "http://hauntedhouses.com/california/mission-san-luis-obispo-de-tolosa/",
//     "http://hauntedhouses.com/california/paso-robles-inn/",
//     "http://hauntedhouses.com/missouri/the-majestic-restaurant-and-jazz-club/",
//     "http://hauntedhouses.com/new-mexico/church-street-cafe/",
//     "http://hauntedhouses.com/california/fox-theater/",
//     "http://hauntedhouses.com/california/kern-county-museum-pioneer-village/",
//     "http://hauntedhouses.com/new-mexico/hotel-andaluz/",
//     "http://hauntedhouses.com/new-mexico/la-fonda-on-the-plaza-la-plazuela/",
//     "http://hauntedhouses.com/arizona/monte-vista-hotel/",
//     "http://hauntedhouses.com/new-mexico/inn-spa-at-loretto-the-loretto-chapel/",
//     "http://hauntedhouses.com/california/casa-de-desierto-harvey-house-museum/",
//     "http://hauntedhouses.com/new-mexico/oldest-house-museum-de-vargas-house/",
//     "http://hauntedhouses.com/washington/holly-hill-house/",
//     "http://hauntedhouses.com/iowa/redstone-inn-and-suites/",
//     "http://hauntedhouses.com/virginia/george-wythe-house-museum/",
//     "http://hauntedhouses.com/west-virginia/harpers-ferry-guest-house/",
//     "http://hauntedhouses.com/west-virginia/st-peters-church/",
//     "http://hauntedhouses.com/west-virginia/the-harper-house-museum/",
//     "http://hauntedhouses.com/west-virginia/harpers-ferry-national-park/",
//     "http://hauntedhouses.com/iowa/jordan-house/",
//     "http://hauntedhouses.com/virginia/ludwell-paradise-house/",
//     "http://hauntedhouses.com/virginia/the-peyton-randolph-house/",
//     "http://hauntedhouses.com/west-virginia/harpers-ferry-streets-and-buildings/",
//     "http://hauntedhouses.com/alaska/the-case-mulvihill-house/",
//     "http://hauntedhouses.com/new-jersey/the-inn-at-cape-may/",
//     "http://hauntedhouses.com/california/the-padre-hotel/",
//     "http://hauntedhouses.com/south-dakota/fairmont-hotel/",
//     "http://hauntedhouses.com/colorado/colorado-cripple-creek-imperial-hotel/",
//     "http://hauntedhouses.com/south-dakota/wild-bills-bar-and-trading-post/",
//     "http://hauntedhouses.com/south-dakota/deadwood-franklin-hotel/",
//     "http://hauntedhouses.com/florida/peabody-hotel/",
//     "http://hauntedhouses.com/new-jersey/hotel-macomber/",
//     "http://hauntedhouses.com/florida/annie-russell-theatre/",
//     "http://hauntedhouses.com/mississippi/waverley-plantation-house/",
//     "http://hauntedhouses.com/florida/the-philemon-bryan-house/",
//     "http://hauntedhouses.com/louisiana/spring-street-historical-museum/",
//     "http://hauntedhouses.com/mississippi/weaver-errolton-mansion/",
//     "http://hauntedhouses.com/louisiana/oakland-cemetery/",
//     "http://hauntedhouses.com/louisiana/the-caddo-parish-courthouse/",
//     "http://hauntedhouses.com/arizona/pioneer-village-merritt-farm/",
//     "http://hauntedhouses.com/arizona/pioneer-village-yellow-victorian/",
//     "http://hauntedhouses.com/arizona/pioneer-village/",
//     "http://hauntedhouses.com/arizona/pioneer-village-community-church/",
//     "http://hauntedhouses.com/arizona/pioneer-village-saloon-and-telephone-museum/",
//     "http://hauntedhouses.com/arizona/pioneer-village-sheriffs-office-jail/",
//     "http://hauntedhouses.com/arizona/phoenix/rosson-house-museum/",
//     "http://hauntedhouses.com/texas/goodman-legrand-house-and-museum/",
//     "http://hauntedhouses.com/louisiana/shreveport-municipal-auditorium/",
//     "http://hauntedhouses.com/louisiana/the-logan-mansion/",
//     "http://hauntedhouses.com/arizona/the-old-spaghetti-factory/",
//     "http://hauntedhouses.com/texas/the-swenson-house-museum/",
//     "http://hauntedhouses.com/mississippi/temple-heights-mansion/",
//     "http://hauntedhouses.com/texas/the-paramount-theatre/",
//     "http://hauntedhouses.com/arizona/san-carlos-hotel/",
//     "http://hauntedhouses.com/texas/the-grace-cultural-center-museum/",
//     "http://hauntedhouses.com/texas/bonner-whitaker-mcclendon-house-museum/",
//     "http://hauntedhouses.com/california/the-uss-hornet-sea-air-and-space-museum/",
//     "http://hauntedhouses.com/arizona/red-buffalo-trading-company/",
//     "http://hauntedhouses.com/arizona/o-k-corral/",
//     "http://hauntedhouses.com/arizona/cafe-margarita/",
//     "http://hauntedhouses.com/virginia/the-brick-house-tavern/",
//     "http://hauntedhouses.com/virginia/the-williamsburg-public-gaol-museum/",
//     "http://hauntedhouses.com/arizona/larian-motel/",
//     "http://hauntedhouses.com/virginia/the-orrell-house/",
//     "http://hauntedhouses.com/arizona/buford-house/",
//     "http://hauntedhouses.com/virginia/edgewood-plantation-bed-and-breakfast/",
//     "http://hauntedhouses.com/arizona/crystal-palace-saloon/",
//     "http://hauntedhouses.com/arizona/tombstone-bordello-b-b/",
//     "http://hauntedhouses.com/arizona/tombstone-streets/",
//     "http://hauntedhouses.com/virginia/westover-plantation/",
//     "http://hauntedhouses.com/virginia/centre-hill-museum/",
//     "http://hauntedhouses.com/virginia/virginia-state-executive-mansion/",
//     "http://hauntedhouses.com/virginia/state-capitol-building/",
//     "http://hauntedhouses.com/virginia/dodsons-tavern/",
//     "http://hauntedhouses.com/virginia/saint-george-episcopal-chapel/",
//     "http://hauntedhouses.com/virginia/the-chimneys/",
//     "http://hauntedhouses.com/virginia/dark-star-saloon/",
//     "http://hauntedhouses.com/virginia/rising-sun-tavern/",
//     "http://hauntedhouses.com/virginia/mary-washington-house-museum/",
//     "http://hauntedhouses.com/georgia/juliette-gordon-lowe-house-museum/",
//     "http://hauntedhouses.com/colorado/denver-union-station/"
// ];

// const scrapeDirectory = (startIndex) => {
//     const promises = [];
    
//     for (let i=startIndex;i<(startIndex + 25);i++) {
//         if (i >= linksToScrape.length) break;

//         console.log(`Link added: ${linksToScrape[i]}`);
//         promises.push(axios.get(linksToScrape[i]));
//     }
    
//     axios.all(promises).then((response) => {
//         for (let i=0;i<response.length;i++) {
//             const $ = cheerio.load(response[i].data);
    
//             $('.content-post--link').each((index, element) => {
//                 console.log(element.attribs.href);
//                 scrapedLinks.push(element.attribs.href);
//             });
//         }
//     }).then(() => {
//         fs.writeFile(`output-${startIndex}.txt`, JSON.stringify(scrapedLinks, null, 2), (err) => {
//             if (err) return err;
    
//             console.log('Done');
//         });
//     }).catch(err => {
//         console.log(err);
//     });
// }

// const scrapeLocations = (startIndex) => {
//     const promises = [];
    
//     for (let i=startIndex;i<(startIndex + 25);i++) {
//         if (i >= locationsToScrape.length) break;

//         console.log(`Link added: ${locationsToScrape[i]}`);
//         promises.push(axios.get(locationsToScrape[i]));
//     }
    
//     axios.all(promises).then((response) => {

//         for (let i=0;i<response.length;i++) {
//             const $ = cheerio.load(response[i].data);
            
//             // title: .single-post--title
//             $('.single-post--title').each((index, element) => {
//                 let location = {
//                     title: element.children[0].data
//                 };
//                 scrapedLocations.push(location);
//             });

//             // image_url: .single-post--thumbnail
//             $('.single-post--thumbnail').each((index, element) => {
//                 let url = element.attribs.style.slice(22, (element.attribs.style.length - 3));
//                 scrapedLocations[i].image_url = url;
//             });

//             // more_infor_url: from response.data
//             for (let k=0;k<scrapedLocations.length;k++) {
//                 let url = 'http://hauntedhouses.com' + response[k].request.path;
//                 scrapedLocations[k].more_info_url = url;
                
//             }

//             for (let k=0;k<scrapedLocations.length;k++) {
//                 scrapedLocations[i].description = $('.bullet h4 em').text();
//             }

//             // address: taken from p tag after h2 with text = LOCATION
//             for (let k=0;k<scrapedLocations.length;k++) {
//                 scrapedLocations[i].address = $('h2:contains("LOCATION") + p').text();
//             }
//         }
//     }).then(() => {
//         // at top of file, require Location model
//         // bulk insert data into sequelize db
//         bulkCreate([{
//           title: '',
// 		  address: '',
// 		  image_url: '',
// 		  more_info_url: '', 
// 		  description: ''
//         }])
        
//         console.log('// TODO: Write data to db');
//         console.log(scrapedLocations);
//     }).catch(err => {
//         console.log(err);
//     });
// };


// switch (process.argv[2]) {
//     case 'directory':
//         scrapeDirectory(parseInt(process.argv[3]));
//         break;
//     case 'locations': 
//         scrapeLocations(parseInt(process.argv[3]));
//         break;
// }



// // axios.get('http://hauntedhouses.com/').then(response => {
// //     const $ = cheerio.load(response.data);


// // $('nav.main-navigation').each((i, element) => {
// //     const link = $(element)
// //         .find('a')
// //         .attr('href'); 

// //         console.log(link);
// //     });
// // });

// //     $('li.menu-item-type-taxonomy').each((i, element) => {
// //         const link = $(element)
// //         .find('a')
// //         .attr('href');

// //         console.log(link);

// //     });
// // });

// //const h3 = $('h3.component-map--header').text();
// //const path = $('path.state js-state').text();